#This will be the hostanme of our Eureka server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #So that this service does not register itself with Eureka
    fetch-registry: false #So that this service does not fetch the registry from Eureka
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761
#To tell the eureka server to fetch the configuration from the config server
spring:
  application:
    name: discovery-server