eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8070

spring:
  application:
    name: product-server #The same name as the file yml in the config-server
  datasource:
        url: jdbc:mysql://localhost:3306/ecommerce-product-microservice?createDatabaseIfNotExist=true
        username: root
        password: mimi019mimi
        driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect




management:
  tracing:
    sampling:
      probability: 1.0

resilience4j:
    retry:
        instances:
            myRetry:
                max-attempts: 1
                waitDuration: 100ms
    ratelimiter:
        instances:
            myRateLimiter:
                limit-for-period: 1
                limit-refresh-period: 1s
                timeout-duration: 100ms
    circuitbreaker:
        instances:
            productService:
                registerHealthIndicator: true
                slidingWindowSize: 2
                failureRateThreshold: 50
                waitDurationInOpenState: 1s
                permittedNumberOfCallsInHalfOpenState: 1
                minimumNumberOfCalls: 2
                eventConsumerBufferSize: 10