eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce-user-microservice?createDatabaseIfNotExist=true
    username: root
    password: mimi019mimi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
#  prometheus:
#    metrics:
#      export:
#        enabled: true

resilience4j:
    retry:
        instances:
            myRetry:
                max-attempts: 3
                waitDuration: 500ms
    ratelimiter:
        instances:
            myRateLimiter:
                limit-for-period: 5
                limit-refresh-period: 1s
                timeout-duration: 500ms
    circuitbreaker:
        instances:
            productService:
                registerHealthIndicator: true
                slidingWindowSize: 100
                permittedNumberOfCallsInHalfOpenState: 10
                minimumNumberOfCalls: 10
                waitDurationInOpenState: 10000
                failureRateThreshold: 50
                eventConsumerBufferSize: 10