eureka:
  client:
    register-with-eureka: false


spring:
  application:
    name: gateway-server #The same name as the yml file in the config server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090 #Where the api should forward the request
          predicates: #When the path contains the following pattern , it should redirect to the uri
            - Path=/students/**
        - id: products
          uri: http://localhost:8070 #Where the api should forward the request
          predicates: #When the path contains the following pattern , it should redirect to the uri
            - Path=/schools/**

server:
  port: 8222
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
#  prometheus:
#    metrics:
#      export:
#        enabled: true